### ISSUE TITLE
New Categories

### ISSUE THREAD

**Issue by Paskunyak** [Youppi3/flaskexample#20]
Accessories & Tools: 1300-1307, 1310, 1315, 1316
Epoxies and Adhesives: 1201, 1518, 1527, 1555, 1557, 1566
Adhesive and Glue Removers: 3200, 1824, 3207, 3230
Paint & Varnish Removers: 1800, 1801, 1806, 1820, 1700, 1706, 1897, 3200, 3208
Finishing Oils: 1802, 1807, 2707, 1702, 2142, 2146, 2147, 2143, 760, 2100
Varnishes and Polyurethanes:  1417, 1805, 1815, 1817, 2705, 1809
Paint & Wallpaper Primers: 3100, 3107, 3133, 3150, 3211, 1822, 1823
Wood Stains & Varnish Stains: 400, 700, 760, 770, 3220
Waxes, Polishes & Cleaners: 1600, 1803, 1804, 1821, 2101, 2102, 2103, 2104
Bathtub Reglazing Epoxy:  8100, 8170, 11101, 8172, 8175, 8200, 7900
Solvents:  9000, 9001, 9008

**Comment by Youppi3** [comment]
closed as of 59aa5546ac795d70dda42b916bcaf4870378497e
